### ISSUE TITLE
Exception when importing DEIPcK or DEWFcK project

### ISSUE THREAD

**Issue by lstandage** [chipKIT32/chipKIT-importer#29]
I'm getting an exception when importing the WiFiScan example from the DEWFcK examples folder:

```
java.nio.file.InvalidPathException: Illegal char <:> at index 6: from C:\Users\c15009\AppData\Local\Arduino15\packages\chipKIT\hardware\pic32\1.4.3\libraries\DEIPcK/DEIPcK.h:66,
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.microchip.mplab.nbide.embedded.chipkit.importer.ArduinoBuilderRunner$1.lambda$visitFile$0(ArduinoBuilderRunner.java:236)
	at com.microchip.mplab.nbide.embedded.chipkit.importer.NativeProcessRunner.runNativeProcess(NativeProcessRunner.java:87)
	at com.microchip.mplab.nbide.embedded.chipkit.importer.NativeProcessRunner.runNativeProcess(NativeProcessRunner.java:66)
	at com.microchip.mplab.nbide.embedded.chipkit.importer.NativeProcessRunner.runNativeProcess(NativeProcessRunner.java:62)
[catch] at com.microchip.mplab.nbide.embedded.chipkit.importer.ArduinoBuilderRunner$1.visitFile(ArduinoBuilderRunner.java:254)
	at com.microchip.mplab.nbide.embedded.chipkit.importer.ArduinoBuilderRunner$1.visitFile(ArduinoBuilderRunner.java:217)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.microchip.mplab.nbide.embedded.chipkit.importer.ArduinoBuilderRunner.findAuxLibraryPaths(ArduinoBuilderRunner.java:217)
	at com.microchip.mplab.nbide.embedded.chipkit.importer.ArduinoBuilderRunner.preprocess(ArduinoBuilderRunner.java:101)
	at com.microchip.mplab.nbide.embedded.chipkit.importer.ChipKitProjectImporter.preprocessSourceProject(ChipKitProjectImporter.java:309)
	at com.microchip.mplab.nbide.embedded.chipkit.importer.ChipKitProjectImporter.execute(ChipKitProjectImporter.java:174)
	at com.microchip.mplab.nbide.embedded.chipkit.wizard.ImportWorker.importChipKitProjectFiles(ImportWorker.java:275)
	at com.microchip.mplab.nbide.embedded.chipkit.wizard.ImportWorker.createProjectFromChipKit(ImportWorker.java:189)
	at com.microchip.mplab.nbide.embedded.chipkit.wizard.ImportWorker.invokeImporterTasks(ImportWorker.java:144)
	at com.microchip.mplab.nbide.embedded.chipkit.wizard.ImportWorker.doInBackground(ImportWorker.java:94)
	at com.microchip.mplab.nbide.embedded.chipkit.wizard.ImportWorker.doInBackground(ImportWorker.java:72)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
However, it doesn't seem to affect the import. I can compile it and debug.

**Comment by gholdys** [comment]
I'm on it...
